type: task
name: Task
description: ''
help: ''
has_title: true
title_label: Title
settings:
  node:
    preview: 1
    options:
      status: true
      promote: true
      sticky: false
      revision: false
    submitted: true
status: true
uuid: 751c2b55-976c-408d-a000-0cb93ebd3f93
langcode: en
dependencies: {  }
